spring:
  application:
    name: ship-managerment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ship_manager
    username: root
    password: [your-db-password]
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      username: default
      password: [your-redis-password]
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  public-Key: classpath:keys/public_key.pem
  private-Key: classpath:keys/private_key.pem

expire:
  token:
    access: 43200 # 60 * 24 * 30 minutes
cloud:
  tencent:
    cos:
      bucket-name: [tencent.cos.bucket-name]
      default-expires-seconds: 3600
      safety-marge-seconds: 300
      upload-expires-seconds: 300
  biz-prefix: [biz-prefix]